
platform :ios, '9.0'

plugin 'cocoapods-binary-bel'


use_frameworks!

target 'demo' do
  pod 'Alamofire', :binary => true
  pod 'SnapKit',"4.2.0", :binary => true

  # 4.0.1

end



# Uncomment the next line to define a global platform for your project
